# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lossCpp <- function(xy, lambda, radius, ED, ThreeD, ToleranceofLoss, maximumStep, ToleranceofStepsize, proportional, ALPHA, Bool) {
    .Call(`_vennplot_loop_R`, xy, lambda, radius, ED, ThreeD, ToleranceofLoss, maximumStep, ToleranceofStepsize, proportional, ALPHA, Bool)
}

transCpp <- function(xy, radius, radiusvec, radiusall) {
    .Call(`_vennplot_trans_R`, xy, radius, radiusvec, radiusall)
}

allDisjointCpp <- function(xy1, xy2, radius1, radius2, delta) {
    .Call(`_vennplot_alldis_R`, xy1, xy2, radius1, radius2, delta)
}

closeCpp <- function(xy1, xy2, radius1, radius2, delta, direc) {
    .Call(`_vennplot_close_R`, xy1, xy2, radius1, radius2, delta, direc)
}

binaryIndexCpp <- function(M, xy, radius, k, yuan, xuan, num) {
    .Call(`_vennplot_binaryIndexCpp`, M, xy, radius, k, yuan, xuan, num)
}

goThroughPixelCpp <- function(myList, m, num) {
    .Call(`_vennplot_goThroughPixelCpp`, myList, m, num)
}

countCpp <- function(M, Me) {
    .Call(`_vennplot_countCpp`, M, Me)
}

getRidofZeroCpp <- function(M) {
    .Call(`_vennplot_getRidofZeroCpp`, M)
}

binaryIndexThreeDCpp <- function(myList, xy, radius, k, yuan, xuan, zuan, num) {
    .Call(`_vennplot_binaryIndexThreeDCpp`, myList, xy, radius, k, yuan, xuan, zuan, num)
}

goThroughPixelThreeDCpp <- function(list, m, num) {
    .Call(`_vennplot_goThroughPixelThreeDCpp`, list, m, num)
}

allConnectedCpp <- function(xy, radius, ThreeD) {
    .Call(`_vennplot_allConnectedCpp`, xy, radius, ThreeD)
}

distanceCpp <- function(r1, r2, theta1, theta2, S, ThreeD) {
    .Call(`_vennplot_distanceCpp`, r1, r2, theta1, theta2, S, ThreeD)
}

BoolScaleNMCpp <- function(proportional, value, LAMBDA, STRESS) {
    .Call(`_vennplot_BoolScaleNMCpp`, proportional, value, LAMBDA, STRESS)
}

BoolScaleLCpp <- function(proportional, value, stress_n, stress) {
    .Call(`_vennplot_BoolScaleLCpp`, proportional, value, stress_n, stress)
}

BoolDistanceCpp <- function(proportional, value, f1, f2, thetanew, theta) {
    .Call(`_vennplot_BoolDistanceCpp`, proportional, value, f1, f2, thetanew, theta)
}

